#include "webserver.h"
#include "api_handlers.h"
#include "esp_http_server.h"
#include "esp_log.h"

static const char *TAG = "WEBSERVER";
static httpd_handle_t s_server = NULL;

static const char *ROOT_HTML =
"<!DOCTYPE html><html lang=\"pl\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>SIHOS17</title>\n"
"<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
"<link href=\"https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Space+Grotesk:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\n"
"<style>*{box-sizing:border-box}body{margin:0;background:#E9EBEE;font-family:Manrope,sans-serif;min-height:100vh;display:flex;justify-content:center;padding:24px 16px}\n"
"input[type=text],input[type=password]{padding:11px 13px;border:1px solid #E3E5E9;border-radius:11px;font:600 13.5px Manrope,sans-serif;color:#16181D;background:#fff;outline:none}\n"
"input[type=text]:focus,input[type=password]:focus{border-color:#16181D}\n"
"input[type=range]{-webkit-appearance:none;appearance:none;background:transparent}\n"
"input[type=range]::-webkit-slider-runnable-track{height:6px;border-radius:999px;background:#E3E5E9}\n"
"input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:18px;height:18px;border-radius:50%;background:#16181D;margin-top:-6px;cursor:pointer}\n"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}</style></head>\n"
"<body><div id=\"app\"></div><script>\n"
"let METER_KEYS={};\n"
"const IZAR_KEYS=['39BC8A10E66D83F8','51728910E66D83F8'];\n"
"let DETECTED={};\n"
"const _SB=[0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16];\n"
"const _ISB=(function(){const s=[0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16];const inv=new Uint8Array(256);for(let i=0;i<256;i++)inv[s[i]]=i;return inv})();\n"
"\n"
"function _decBlk(blk,w){let s=blk.slice(0);const sr=[0,13,10,7,4,1,14,11,8,5,2,15,12,9,6,3];const ark=function(r){for(let i=0;i<16;i++)s[i]^=w[r*16+i]};ark(10);for(let r=9;r>=1;r--){let t=s.slice(0);for(let i=0;i<16;i++)s[i]=t[sr[i]];for(let i=0;i<16;i++)s[i]=_ISB[s[i]];ark(r);for(let c=0;c<4;c++){const o=c*4,a0=s[o],a1=s[o+1],a2=s[o+2],a3=s[o+3];s[o]=_ml(a0,14)^_ml(a1,11)^_ml(a2,13)^_ml(a3,9);s[o+1]=_ml(a0,9)^_ml(a1,14)^_ml(a2,11)^_ml(a3,13);s[o+2]=_ml(a0,13)^_ml(a1,9)^_ml(a2,14)^_ml(a3,11);s[o+3]=_ml(a0,11)^_ml(a1,13)^_ml(a2,9)^_ml(a3,14)}}let t=s.slice(0);for(let i=0;i<16;i++)s[i]=t[sr[i]];for(let i=0;i<16;i++)s[i]=_ISB[s[i]];ark(0);return s}\n"
"function _kex(key){const rc=[1,2,4,8,16,32,64,128,0x1b,0x36];const w=new Array(176);for(let i=0;i<16;i++)w[i]=key[i];for(let i=16;i<176;i+=4){let t=[w[i-4],w[i-3],w[i-2],w[i-1]];if(i%16===0){t=[_SB[t[1]]^rc[i/16-1],_SB[t[2]],_SB[t[3]],_SB[t[0]]]}for(let j=0;j<4;j++)w[i+j]=w[i-16+j]^t[j]}return w}\n"
"function _ml(a,b){let r=0;for(let i=0;i<8;i++){if(b&1)r^=a;a=_xt(a);b>>=1}return r}\n"
"function _xt(a){a<<=1;if(a&0x100)a^=0x11b;return a&0xff}\n"
"function aesCbcDecrypt(keyHex,iv,data){const key=hexToBytes(keyHex);const w=_kex(key);const out=new Uint8Array(data.length);let prev=Array.from(iv);for(let off=0;off<data.length;off+=16){const blk=Array.from(data.slice(off,off+16));const dec=_decBlk(blk,w);for(let i=0;i<16;i++)out[off+i]=dec[i]^prev[i];prev=blk}return out}\n"
"function amiplusDecode(b){let ci=-1;for(let i=10;i<Math.min(b.length,16);i++){if(b[i]===0x7A){ci=i;break}}if(ci<0)return[];const payload=b.slice(ci+5);const recs=parseDifVif(payload);const out=[];let ve=0,vp=0,vv=0;for(const r of recs){if(r.quantity==='Energy'&&!r.tariff&&ve<1){out.push({field:'energia_kwh',value:r.value,unit:'kWh'});ve++}else if(r.quantity==='Power'&&vp<1){out.push({field:'moc_kw',value:r.value,unit:'kW'});vp++}else if(r.quantity==='Voltage'&&vv<3){out.push({field:'napiecie_l'+(vv+1)+'_v',value:r.value,unit:'V'});vv++}}return out}\n"
"async function amiplusDecrypt(braw){const b=removeBlockCrc(braw);const id=meterId(b).toLowerCase();const key=METER_KEYS[id];if(!key)return 'NOKEY';let ci=-1;for(let i=10;i<Math.min(b.length,20);i++)if(b[i]===0x7A){ci=i;break}if(ci<0)return null;const acc=b[ci+1];const iv=new Uint8Array(16);for(let i=0;i<8;i++)iv[i]=b[2+i];for(let i=8;i<16;i++)iv[i]=acc;const encStart=ci+5;const enc=b.slice(encStart,encStart+Math.floor((b.length-encStart)/16)*16);const dec=aesCbcDecrypt(key,iv,enc);if(!dec||dec[0]!==0x2F||dec[1]!==0x2F)return 'BADKEY';return parseDifVif(dec.slice(2))}\n"
"async function apatorDecode(braw){const b=removeBlockCrc(braw);const id=meterId(b).toLowerCase();const key=METER_KEYS[id];let content=null;let ci=-1;for(let i=10;i<20;i++){if(b[i]===0x7A){ci=i;break}}if(ci<0)return null;if(key){const acc=b[ci+1];const iv=new Uint8Array(16);for(let i=0;i<8;i++)iv[i]=b[2+i];for(let i=8;i<16;i++)iv[i]=acc;const encStart=ci+5;const enc=b.slice(encStart,encStart+Math.floor((b.length-encStart)/16)*16);const dec=aesCbcDecrypt(key,iv,enc);if(dec&&dec[0]===0x2F&&dec[1]===0x2F){content=dec.slice(2)}}if(!content){let cs=ci+5;if(b[cs]===0x2F&&b[cs+1]===0x2F)cs+=2;content=b.slice(cs)}let i=8,total=null;while(i<content.length){const c=content[i];if(c===0xFF)break;const size=apatorRegSize(c);i++;if(size===-1||i+size>content.length)break;if(c===0x10&&size===4){total=(content[i]|(content[i+1]<<8)|(content[i+2]<<16)|(content[i+3]<<24))>>>0}i+=size}return total!==null?total/1000:null}\n"
"function apatorRegSize(c){switch(c){case 0x00:return 4;case 0x01:return 3;case 0xA1:case 0x10:return 4;case 0x11:return 2;case 0x40:return 6;case 0x41:return 2;case 0x42:return 4;case 0x43:return 2;case 0x44:return 3;case 0x71:return 9;case 0x72:return 13;case 0x73:return 17;case 0x74:return 21;case 0x75:return 25;case 0x76:return 29;case 0x77:return 33;case 0x78:return 37;case 0x79:return 41;case 0x7A:return 45;case 0x7B:return 49;case 0x80:case 0x81:case 0x82:case 0x83:case 0x84:case 0x86:case 0x87:return 10;case 0x85:case 0x88:case 0x8F:return 11;case 0x8A:return 9;case 0x8B:case 0x8C:return 6;case 0x8E:return 7;case 0xA0:return 4;case 0xA2:return 1;case 0xA3:return 7;case 0xA4:return 4;case 0xA5:case 0xA9:case 0xAF:return 1;case 0xA6:return 3;case 0xA7:case 0xA8:case 0xAA:case 0xAB:case 0xAC:case 0xAD:return 2;case 0xB0:return 5;case 0xB1:return 8;case 0xB2:return 16;case 0xB3:return 8;case 0xB4:return 2;case 0xB5:return 16;case 0xB6:case 0xB7:case 0xB8:case 0xB9:case 0xBA:case 0xBB:case 0xBC:case 0xBD:case 0xBE:case 0xBF:return 3;case 0xC0:case 0xC1:case 0xC2:case 0xC3:case 0xC4:case 0xC5:case 0xC6:case 0xC7:return 3;case 0xD0:case 0xD3:return 3;case 0xF0:return 4}return -1}\n"
"function bcd(b,p,n){let s='';for(let i=n-1;i>=0;i--)s+=((b[p+i]>>4)&15).toString()+(b[p+i]&15).toString();return parseInt(s,10)}\n"
"function convKey(h){const b=hexToBytes(h);return(u32be(b,0)^u32be(b,4))>>>0}\n"
"function crc16w(d,off,len){let crc=0;for(let i=0;i<len;i++){let b=d[off+i];for(let j=0;j<8;j++){if((((crc&0x8000)>>8)^(b&0x80))!==0){crc=((crc<<1)^0x3D65)&0xFFFF}else{crc=(crc<<1)&0xFFFF}b=(b<<1)&0xFF}}return(~crc)&0xFFFF}\n"
"function dVIF(vif){const v=vif&0x7F;if(v<=7)return{q:'Energy',u:'kWh',s:Math.pow(10,v-3)/1000};if(v>=8&&v<=15)return{q:'Energy',u:'kWh',s:Math.pow(10,v-8)/3600000};if(v>=16&&v<=23)return{q:'Volume',u:'m3',s:Math.pow(10,(v&7)-6)};if(v>=40&&v<=47)return{q:'Power',u:'kW',s:Math.pow(10,(v&7)-3)/1000};if(v>=56&&v<=63)return{q:'Flow',u:'m3h',s:Math.pow(10,(v&7)-6)};if(v===0x6C)return{q:'Date',u:'',s:1};if(v===0x6D)return{q:'DateTime',u:'',s:1};return{q:'Unknown',u:'',s:1}}\n"
"function dVIFE_FD(vife){const v=vife&0x7F;if(v>=0x40&&v<=0x4F)return{q:'Voltage',u:'V',s:Math.pow(10,(v&15)-9)};if(v>=0x50&&v<=0x5F)return{q:'Current',u:'A',s:Math.pow(10,(v&15)-12)};return{q:'Unknown',u:'',s:1}}\n"
"async function decodeFrame(hex){const b=hexToBytes(hex);if(b.length<10)return null;const o={id:meterId(b),manufacturer:manuf(b),version:b[8],medium:b[9],rssi:0,fields:[],_hex:hex};if(o.manufacturer==='SAP'&&o.medium===0x01){o.type='izar';const r=izarDecode(b);if(r){o.fields.push({field:'total_m3',value:r.total_m3,unit:'m3'});if(r.poprzedni_miesiac_m3!==undefined)o.fields.push({field:'poprzedni_miesiac_m3',value:r.poprzedni_miesiac_m3,unit:'m3'});if(r.data_odczytu)o.fields.push({field:'data_odczytu',value:r.data_odczytu,unit:''});if(r.bateria_lata!==undefined)o.fields.push({field:'bateria_lata',value:r.bateria_lata,unit:'lat'});if(r.okres_nadawania_s!==undefined)o.fields.push({field:'okres_nadawania_s',value:r.okres_nadawania_s,unit:'s'});if(r.alarm)o.fields.push({field:'alarm',value:r.alarm,unit:''})}}else if(o.medium===0x02){o.type='amiplus';const recs=await amiplusDecrypt(b);if(recs==='NOKEY')o._keyError='nokey';else if(recs==='BADKEY')o._keyError='badkey';else if(Array.isArray(recs)){let ve=0,vpr=0,vp=0,vpp=0,vv=0;const et={},pt={};for(const r of recs){if(r.quantity==='Energy'&&!r.backflow){if(!r.tariff&&ve<1){o.fields.push({field:'energia_kwh',value:r.value,unit:'kWh'});ve++}else if(r.tariff>=1&&r.tariff<=3&&!et[r.tariff]){o.fields.push({field:'energia_t'+r.tariff+'_kwh',value:r.value,unit:'kWh'});et[r.tariff]=1}}else if(r.quantity==='Energy'&&r.backflow){if(!r.tariff&&vpr<1){o.fields.push({field:'produkcja_kwh',value:r.value,unit:'kWh'});vpr++}else if(r.tariff>=1&&r.tariff<=3&&!pt[r.tariff]){o.fields.push({field:'produkcja_t'+r.tariff+'_kwh',value:r.value,unit:'kWh'});pt[r.tariff]=1}}else if(r.quantity==='Power'&&!r.backflow&&vp<1){o.fields.push({field:'moc_kw',value:r.value,unit:'kW'});vp++}else if(r.quantity==='Power'&&r.backflow&&vpp<1){o.fields.push({field:'moc_produkcji_kw',value:r.value,unit:'kW'});vpp++}else if(r.quantity==='Voltage'&&vv<3){o.fields.push({field:'napiecie_l'+(vv+1)+'_v',value:r.value,unit:'V'});vv++}}}}else if(o.manufacturer==='APA'&&o.medium===0x07&&o.version===0x1a){o.type='op041a';const recs=await amiplusDecrypt(b);if(recs==='NOKEY')o._keyError='nokey';else if(recs==='BADKEY')o._keyError='badkey';else if(Array.isArray(recs)){let vv=0;for(const r of recs){if(r.quantity==='Volume'&&vv<1){o.fields.push({field:'total_m3',value:r.value,unit:'m3'});vv++}}}}else if(o.manufacturer==='APA'&&(o.medium===0x07||o.medium===0x06)){o.type='apator';const t=await apatorDecode(b);if(t!==null)o.fields.push({field:'total_m3',value:t,unit:'m3'})}else if(o.manufacturer==='APA'){o.type='apator162'}else if(o.manufacturer==='AMX'&&o.medium===0x03){o.type='unismart';const recs=await amiplusDecrypt(b);if(recs){let vt=0;for(const r of recs){if(r.quantity==='Volume'&&vt<1){o.fields.push({field:'total_m3',value:r.value,unit:'m3'});vt++}}}}else if(o.manufacturer==='SON'&&o.medium===0x04){o.type='sontex';const recs=await amiplusDecrypt(b);if(recs==='NOKEY')o._keyError='nokey';else if(recs==='BADKEY')o._keyError='badkey';else if(Array.isArray(recs)){let ve=0,vv=0;for(const r of recs){if(r.quantity==='Energy'&&ve<1){o.fields.push({field:'energia_kwh',value:r.value,unit:'kWh'});ve++}else if(r.quantity==='Volume'&&vv<1){o.fields.push({field:'total_m3',value:r.value,unit:'m3'});vv++}}}}else if(o.medium===0x03){o.type='gas'}else{o.type='unknown'}if(!o.fields.length&&!o._keyError&&frameIsEncrypted(b)){o._keyError=METER_KEYS[(o.id||'').toLowerCase()]?'badkey':'nokey'}return o}\n"
"function driverName(t){return({izar:'Diehl IZAR (woda)',amiplus:'Apator Amiplus (energia el.)',apator:'Apator AT-WMBUS-16-2 (woda)',apator162:'Apator 16-2 (woda)',unismart:'Apator UNISMART (gaz)',gas:'Licznik gazu',electricity:'Licznik energii',water:'Licznik wody',unknown:'Nieznany'})[t]||t}\n"
"function fieldGroup(m,fields,dash){return fields.map(function(x){var v=(typeof x.value==='number'&&isFinite(x.value))?((x.unit==='V'||x.unit==='s'||x.unit==='W')?Math.round(x.value).toString():(x.unit==='lat'?x.value.toFixed(1):(x.unit==='m3'||x.unit==='kWh'||x.unit==='kW')?x.value.toFixed(3):x.value.toFixed(2))):x.value;var trackable=(x.unit==='kWh'||x.unit==='kW'||x.unit==='V'||x.unit==='m3');var key=m.id+':'+x.field;var on=window.TRACKED&&window.TRACKED[key];var ic;if(dash){ic=(trackable&&on)?'<span class=\"hist-ic\" data-hkey=\"'+key+'\" title=\"Pokaz wykres w Historii\">'+histIcon()+'</span>':'';}else{ic=trackable?'<span class=\"tile-ic '+(on?'on':'')+'\" data-tkey=\"'+key+'\" title=\"'+(on?'Śledzone w historii':'Dodaj do historii')+'\">'+(on?'\\u2713':'+')+'</span>':'';}return '<div class=\"tile\"><div class=\"tile-k\">'+x.field.replace(/_/g,' ')+'</div><div class=\"tile-v\">'+v+' <small>'+x.unit+'</small></div>'+ic+'</div>'}).join('')}\n"
"function fieldUnit(key){if(!key)return '';if(key.indexOf('kwh')>=0||key.indexOf('energia')>=0||key.indexOf('produkcja')>=0)return 'kWh';if(key.indexOf('moc')>=0)return 'kW';if(key.indexOf('napiecie')>=0)return 'V';if(key.indexOf('m3')>=0)return 'm3';return ''}\n"
"function fmt(tag,el){if(!el)return;if(!tag){el.textContent='Brak wydania';return}var same=cur&&(tag===cur||tag==='v'+cur||tag.replace(/^v/,'')===cur.replace(/^v/,''));if(same){el.innerHTML='<span style=\\\"color:var(--ok)\\\">Masz najnowszą ('+tag+')</span>'}else{el.innerHTML='Dostępna: <b style=\\\"color:var(--accent)\\\">'+tag+'</b>'}}\n"
"function fmtBytes(b){if(b>=1048576)return(b/1048576).toFixed(1)+' MB';if(b>=1024)return(b/1024).toFixed(1)+' KB';return b+' B'}\n"
"function fmtUp(ms){let s=ms/1000|0,d=s/86400|0;s%=86400;let h=s/3600|0;s%=3600;let m=s/60|0;return d>0?d+'d '+h+'h '+m+'m':h>0?h+'h '+m+'m':m+'m'}\n"
"function fmtUpt(sec){const d=Math.floor(sec/86400),h=Math.floor((sec%86400)/3600),m=Math.floor((sec%3600)/60);let r='';if(d>0)r+=d+'d ';if(h>0||d>0)r+=h+'h ';r+=m+'m';return r}\n"
"function frameIsEncrypted(braw){var b=removeBlockCrc(braw);if(b.length<11)return false;var ci=b[10];var confPos=-1;if(ci===0x7A){confPos=13}else if(ci===0x72){confPos=19}else{for(var i=10;i<b.length-3;i++){if(b[i]===0x7A){confPos=i+3;break}if(b[i]===0x72){confPos=i+9;break}}}if(confPos<0||confPos>=b.length)return false;var conf=b[confPos];var mode=conf&0x1f;var blocks=(conf>>4)&0x0f;if(mode===5||mode===7||mode===13)return true;if(blocks>0)return true;return false}\n"
"function hexToBytes(h){const b=new Uint8Array(h.length/2);for(let i=0;i<b.length;i++)b[i]=parseInt(h.substr(i*2,2),16);return b}\n"
"function histColor(id){if(!id)return '#3d8bff';if(id.indexOf('m3')>=0)return '#378add';if(id.indexOf('kwh')>=0||id.indexOf('energia')>=0||id.indexOf('produkcja')>=0)return '#ef9f27';if(id.indexOf('gaz')>=0)return '#d85a30';if(id.indexOf('napiecie')>=0)return '#1d9e75';if(id.indexOf('moc')>=0)return '#ef9f27';return '#3d8bff'}\n"
"function histPeriodLabel(){var r=histState.res,a=histState.anchor?new Date(histState.anchor*1000):new Date();var p=function(n){return(n<10?'0':'')+n};var mn=['sty','lut','mar','kwi','maj','cze','lip','sie','wrz','paź','lis','gru'];var now=new Date();if(r==='hour'||r==='day1'){var isNow=(a.toDateString()===now.toDateString());return{lbl:isNow?'Teraz':'Dzień',date:p(a.getDate())+' '+mn[a.getMonth()]+' '+a.getFullYear()}}if(r==='day')return{lbl:'Tydzień',date:p(a.getDate())+' '+mn[a.getMonth()]+' '+a.getFullYear()};if(r==='month')return{lbl:'Miesiąc',date:mn[a.getMonth()]+' '+a.getFullYear()};if(r==='year')return{lbl:'Rok',date:''+a.getFullYear()};if(r==='rt')return{lbl:'Na żywo',date:''};return{lbl:'',date:''}}\n"
"function izarDecode(frame){for(const kh of IZAR_KEYS){let k=convKey(kh);k=(k^u32be(frame,2))>>>0;k=(k^u32be(frame,6))>>>0;k=(k^u32be(frame,12))>>>0;const size=frame.length-17;if(size<=0)continue;const dec=new Uint8Array(size);let kk=k;for(let i=0;i<size;i++){for(let j=0;j<8;j++){const bit=(((kk>>>1)&1)^((kk>>>2)&1)^((kk>>>11)&1)^((kk>>>31)&1))&1;kk=((kk<<1)|bit)>>>0}dec[i]=frame[i+17]^(kk&0xFF)}if(dec[0]===0x4B){const r={};r.total_m3=((dec[1]|(dec[2]<<8)|(dec[3]<<16)|(dec[4]<<24))>>>0)/1000;if(size>=9){r.poprzedni_miesiac_m3=((dec[5]|(dec[6]<<8)|(dec[7]<<16)|(dec[8]<<24))>>>0)/1000}if(size>=11){let y=((dec[10]&0xF0)>>1)+((dec[9]&0xE0)>>5);y+=(y>80?1900:2000);const mo=dec[10]&0x0F,da=dec[9]&0x1F;r.data_odczytu=y+'-'+(mo<10?'0':'')+mo+'-'+(da<10?'0':'')+da}const cl=removeBlockCrc(frame);if(cl.length>13){r.bateria_lata=(cl[12]&0x1F)/2.0;r.okres_nadawania_s=1<<((cl[11]&0x0F)+2);const leak=(cl[12]>>7)&1,blocked=(cl[12]>>5)&1,backflow=(cl[13]>>7)&1;r.alarm=(leak?'przeciek ':'')+(blocked?'blokada ':'')+(backflow?'cofka':'')||'brak'}return r}}return null}\n"
"function lastSeenStr(tsUnix){if(!tsUnix)return'Ostatni odczyt: --';const d=new Date(tsUnix*1000);const p=n=>(n<10?'0':'')+n;return'Ostatni odczyt: '+p(d.getHours())+':'+p(d.getMinutes())+':'+p(d.getSeconds())+' ['+p(d.getDate())+'.'+p(d.getMonth()+1)+'.'+d.getFullYear()+']'}\n"
"function lbl(ts){var dt=new Date(ts*1000);var p=function(n){return(n<10?'0':'')+n};if(histState.res==='rt')return p(dt.getHours())+':'+p(dt.getMinutes())+':'+p(dt.getSeconds());if(histState.res==='hour'||histState.res==='day1')return dt.getHours()+':00';if(histState.res==='day')return p(dt.getDate())+'.'+p(dt.getMonth()+1);if(histState.res==='month')return p(dt.getMonth()+1)+'.'+dt.getFullYear();return ''+dt.getFullYear()}\n"
"function lblRange(ts){if(histState.res==='hour'||histState.res==='day1'){var dt=new Date(ts*1000);var h=dt.getHours();var h2=(h+1)%24;return h+':00-'+h2+':00'}if(histState.res==='day'){var dt=new Date(ts*1000);var p=function(n){return(n<10?'0':'')+n};return p(dt.getDate())+'.'+p(dt.getMonth()+1)}return lbl(ts)}\n"
"function manuf(b){const m=b[2]|(b[3]<<8);return String.fromCharCode(((m>>10)&0x1F)+64,((m>>5)&0x1F)+64,(m&0x1F)+64)}\n"
"function meterId(b){const h=x=>x.toString(16).padStart(2,'0');return h(b[7])+h(b[6])+h(b[5])+h(b[4])}\n"
"function parseDifVif(payload){const recs=[];let pos=0;while(pos<payload.length){let dif=payload[pos++];if(dif===0x2F)continue;if(dif===0x0F||dif===0x1F)break;let tariff=0,ext=dif&0x80;while(ext&&pos<payload.length){const de=payload[pos++];tariff|=((de>>4)&15);ext=de&0x80}if(pos>=payload.length)break;let vif=payload[pos++];let vi;if(vif===0xFD){const vife=payload[pos++];vi=dVIFE_FD(vife);let e=vife&0x80;while(e&&pos<payload.length){e=payload[pos]&0x80;pos++}}else if(vif&0x80){vi=dVIF(vif);let e=1,bf=false;while(e&&pos<payload.length){if(payload[pos]===0x3C)bf=true;e=payload[pos]&0x80;pos++}vi.bf=bf}else{vi=dVIF(vif)}const r=rdVal(payload,pos,dif);pos+=r.len;if(!r.isStr&&vi.q!=='Unknown'&&vi.q!=='Date'&&vi.q!=='DateTime')recs.push({tariff,quantity:vi.q,unit:vi.u,value:(typeof r.val==='number')?r.val*vi.s:r.val,backflow:vi.bf||false})}return recs}\n"
"function rdVal(b,p,dif){const c=dif&15;switch(c){case 0:return{val:0,len:0};case 1:return{val:(b[p]<<24>>24),len:1};case 2:{let v=b[p]|(b[p+1]<<8);return{val:(v<<16>>16),len:2}}case 3:{let v=b[p]|(b[p+1]<<8)|(b[p+2]<<16);if(v&0x800000)v-=0x1000000;return{val:v,len:3}}case 4:return{val:(b[p]|(b[p+1]<<8)|(b[p+2]<<16)|(b[p+3]<<24))|0,len:4};case 6:{let v=0;for(let i=0;i<6;i++)v+=b[p+i]*Math.pow(2,8*i);return{val:v,len:6}}case 7:{let v=0;for(let i=0;i<8;i++)v+=b[p+i]*Math.pow(2,8*i);return{val:v,len:8}}case 9:return{val:bcd(b,p,1),len:1};case 10:return{val:bcd(b,p,2),len:2};case 11:return{val:bcd(b,p,3),len:3};case 12:return{val:bcd(b,p,4),len:4};case 14:return{val:bcd(b,p,6),len:6};case 13:{const l=b[p];return{val:0,len:l+1,isStr:true}}default:return{val:0,len:0}}}\n"
"function removeBlockCrc(d){if(d.length<12)return d;if(validBlocks(d)){const r=stripBlocks(d);if(r)return r}const L=d[0];const nblk=Math.ceil((L+1-10)/16);const expLen=(L+1)+2+nblk*2;if(d.length===expLen){const r=stripBlocks(d);if(r&&(r[10]===0x7A||r[10]===0x72))return r}return d}\n"
"function stripAnsi(s){return s.replace(/\\x1b\\[[0-9;]*m/g,'')}\n"
"function stripBlocks(d){const ln=d.length;const out=[];for(let i=0;i<10;i++)out.push(d[i]);let pos=12;while(pos+18<=ln){for(let i=0;i<16;i++)out.push(d[pos+i]);pos+=18}if(pos<ln-2){const dl=(ln-2)-pos;for(let i=0;i<dl;i++)out.push(d[pos+i])}if(out.length<11)return null;out[0]=out.length-1;return new Uint8Array(out)}\n"
"function tagClass(t){if(t.includes('elect')||t=='amiplus')return'elec';if(t.includes('water')||t=='izar'||t=='apator162')return'water';if(t=='unismart'||t.includes('gas'))return'gas';return'unk'}\n"
"function tagLabel(t){return({amiplus:'Prad',izar:'Woda',apator162:'Woda',apator:'Woda',unismart:'Gaz',electricity:'Prad',water:'Woda',gas:'Gaz'})[t]||t}\n"
"function timeOnly(tsUnix){if(!tsUnix)return'--:--:--';var d=new Date(tsUnix*1000);var p=function(n){return(n<10?'0':'')+n};return p(d.getHours())+':'+p(d.getMinutes())+':'+p(d.getSeconds())+' ['+p(d.getDate())+'.'+p(d.getMonth()+1)+'.'+d.getFullYear()+']'}\n"
"function u32be(d,o){return((d[o]<<24)|(d[o+1]<<16)|(d[o+2]<<8)|d[o+3])>>>0}\n"
"function validBlocks(d){const ln=d.length;if(ln<12)return false;if(crc16w(d,0,10)!==((d[10]<<8)|d[11]))return false;let pos=12;while(pos+18<=ln){if(crc16w(d,pos,16)!==((d[pos+16]<<8)|d[pos+17]))return false;pos+=18}if(pos<ln-2){const dl=(ln-2)-pos;if(crc16w(d,pos,dl)!==((d[ln-2]<<8)|d[ln-1]))return false}return true}async function loadMeterKeys(){try{const cfg=await(await fetch('/api/config')).json();METER_KEYS={};if(cfg.meters)for(const m of cfg.meters){if(m.key&&m.key.length===32)METER_KEYS[m.id.toLowerCase()]=m.key}}catch(e){}}\n"
"async function saveKey(){const id=document.getElementById('keyid').value.trim();const key=document.getElementById('keyval').value.trim();const msg=document.getElementById('keymsg');if(!id||key.length!==32){msg.className='msg err';msg.textContent='Podaj ID i klucz 32 hex';return}msg.className='msg ok';msg.textContent='Zapisywanie...';try{await fetch('/api/config/meter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id,type:'amiplus',key:key})});METER_KEYS[id.toLowerCase()]=key;msg.textContent='Zapisano klucz dla '+id;document.getElementById('keyval').value='';document.getElementById('keyid').value='';loadSavedMeters();fetchMeters()}catch(e){msg.className='msg err';msg.textContent='Błąd zapisu'}}\n"
"async function saveMeterKey(id,type){const inp=document.getElementById('key-'+id);if(!inp)return;const key=inp.value.trim();if(key.length!==32){alert('Klucz AES musi mieć 32 znaki hex');return}try{await fetch('/api/config/meter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id,type:type,key:key})});inp.value='';METER_KEYS[id.toLowerCase()]=key;fetchMeters()}catch(e){alert('Błąd zapisu')}}\n"
"async function deleteMeter(id){if(!confirm('Usunąć licznik '+id+'?'))return;try{await fetch('/api/config/meter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id,del:1})});delete METER_KEYS[id.toLowerCase()];loadSavedMeters()}catch(e){alert('Błąd usuwania')}}\n"
"async function editMeterName(id){var cur=(window.NAMES&&window.NAMES[(id||'').toLowerCase()])||'';var nn=prompt('Nazwa dla licznika '+id+' (puste = pokaż ID):',cur);if(nn===null)return;nn=nn.trim();try{await fetch('/api/meter/name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id,name:nn})});if(!window.NAMES)window.NAMES={};if(nn)window.NAMES[(id||'').toLowerCase()]=nn;else delete window.NAMES[(id||'').toLowerCase()];fetchMeters()}catch(e){}}\n"
"function editMeter(id){const m=(window._savedMeters||[]).find(function(x){return x.id===id});if(!m)return;document.getElementById('keyid').value=m.id;document.getElementById('keyval').value=m.key||'';const msg=document.getElementById('keymsg');msg.className='msg';msg.textContent='Edytujesz '+id+' - zmien klucz i zapisz';document.getElementById('keyid').scrollIntoView({behavior:'smooth',block:'center'})}\n"
"async function loadSavedMeters(){const el=document.getElementById('saved-list');if(!el)return;try{const cfg=await(await fetch('/api/config')).json();window._savedMeters=cfg.meters||[];if(!cfg.meters||!cfg.meters.length){el.innerHTML='<div class=\"empty\">Brak zapisanych liczników</div>';return}el.innerHTML=cfg.meters.map(function(m){var k=(m.key&&m.key.length===32)?(m.key.substring(0,4)+'...'+m.key.substring(28)):'(brak)';return '<div style=\"padding:8px;border:1px solid var(--bd);border-radius:8px;margin-bottom:6px;display:flex;justify-content:space-between;align-items:center;gap:8px\">'+'<div style=\"flex:1;min-width:0\"><div style=\"font-weight:600\">'+(m.name||m.id)+'</div>'+'<div style=\"font-size:.75rem;color:var(--mut)\">ID: '+m.id+' &middot; klucz: '+k+'</div></div>'+'<div style=\"display:flex;gap:6px\"><button class=\"btn sm-edit\" data-id=\"'+m.id+'\" style=\"margin:0;padding:4px 10px;font-size:.8rem\">Edytuj</button>'+'<button class=\"btn sm-del\" data-id=\"'+m.id+'\" style=\"margin:0;padding:4px 10px;font-size:.8rem;color:#e66\">Usun</button></div></div>'}).join('');el.querySelectorAll('.sm-edit').forEach(function(b){b.addEventListener('click',function(){editMeter(b.getAttribute('data-id'))})});el.querySelectorAll('.sm-del').forEach(function(b){b.addEventListener('click',function(){deleteMeter(b.getAttribute('data-id'))})})}catch(e){el.innerHTML='<div class=\"empty\">Błąd ładowania</div>'}}\n"
"async function fetchMeters(){const m=await fetchFrames();try{const tr=await(await fetch('/api/history/tracked')).json();window.TRACKED={};tr.forEach(function(k){window.TRACKED[k]=true})}catch(e){}try{const pj=await(await fetch('/api/dashboard')).json();window.PINNED={};(pj.pinned||[]).forEach(function(id){window.PINNED[id.toLowerCase()]=true})}catch(e){}try{const nm=await(await fetch('/api/meter/names')).json();window.NAMES={};for(const k in nm)window.NAMES[k.toLowerCase()]=nm[k]}catch(e){}try{const cfg=await(await fetch('/api/config')).json();window._savedMeters=cfg.meters||[]}catch(e){}try{window._histList=await(await fetch('/api/history/list')).json()}catch(e){if(!window._histList)window._histList=[]}const dm=document.getElementById('dash-meters'),ml=document.getElementById('meters-list');if(ml)ml.innerHTML=m.length?m.map(function(x){return meterCard(x)}).join(''):'<div class=\"empty\">Brak wykrytych liczników</div>';if(dm){var saved=window._savedMeters||[];var pins=Object.keys(window.PINNED||{}).filter(function(id){return window.PINNED[id]});if(!pins.length){dm.innerHTML='<div class=\"empty\">Brak przypiętych liczników. Dodaj w zakładce Liczniki przyciskiem +</div>'}else{dm.innerHTML=pins.map(function(id){var live=m.filter(function(x){return (x.id||'').toLowerCase()===id})[0];if(live)return meterCard(live,true);var sm=saved.filter(function(s){return s.id.toLowerCase()===id.toLowerCase()})[0];return meterCardPending(id,sm)}).join('')}}}\n"
"async function fetchFrames(){try{await loadMeterKeys();const fr=await(await fetch('/api/frames')).json();const byId={};for(const f of fr){const d=await decodeFrame(f.hex);if(!d)continue;d.rssi=f.rssi;d._ts=f.ts;d._tsUnix=f.ts_unix;const prev=byId[d.id];if(!prev){byId[d.id]=d}else{if(f.ts>=prev._ts){const fmap={};for(const x of prev.fields)fmap[x.field]=x;for(const x of d.fields)fmap[x.field]=x;d.fields=Object.values(fmap);byId[d.id]=d}else{const fmap={};for(const x of d.fields)fmap[x.field]=x;for(const x of prev.fields)fmap[x.field]=x;prev.fields=Object.values(fmap)}}}for(const id in byId){const d=byId[id];const old=DETECTED[id];if(old){const fmap={};for(const x of old.fields)fmap[x.field]=x;for(const x of d.fields)fmap[x.field]=x;d.fields=Object.values(fmap)}DETECTED[id]=d}renderRawFrames(fr);return Object.values(DETECTED)}catch(e){return Object.values(DETECTED)}}\n"
"async function fetchStatus(){try{const d=await(await fetch('/api/status')).json();if(d.version){if(window._fwVersion===undefined){window._fwVersion=d.version}else if(window._fwVersion!==d.version){location.reload(true);return}}var setT=function(id,v){var el=document.getElementById(id);if(el)el.textContent=v};var setH=function(id,v){var el=document.getElementById(id);if(el)el.innerHTML=v};const c=document.getElementById('wifiChip'),t=document.getElementById('wifiChipTxt');var verStr=(d.version||'--')+(d.partition?' ['+d.partition+']':'');setT('d-ver',verStr);setT('u-ver',d.version||'--');setT('sys-ver',verStr);setT('side-ver',d.version||'--');setT('d-uptime',fmtUp(d.uptime_ms));setT('d-meters',d.meter_count||0);setT('d-ip',d.ip||'--');setH('d-rssi',(d.wifi_rssi||'--')+'<small> dBm</small>');setT('sys-wifi-net',d.ssid&&d.wifi_state==='connected'?d.ssid:(d.wifi_state==='ap_mode'?'Tryb AP':'Niepołączono'));var ssidIn=document.getElementById('ssid');if(ssidIn&&!ssidIn.value&&d.ssid&&!ssidIn.dataset.touched)ssidIn.placeholder=d.ssid;if(d.wifi_state==='connected'){if(c)c.className='chip ok';if(t)t.textContent=d.ip;setT('d-wifistate','połączono')}else if(d.wifi_state==='ap_mode'){if(c)c.className='chip warn';if(t)t.textContent='Tryb AP';setT('d-wifistate','AP')}else{if(c)c.className='chip err';if(t)t.textContent='Brak WiFi';setT('d-wifistate','--')}}catch(e){}}\n"
"async function fetchSystem(){const el=document.getElementById('sysinfo');if(!el)return;try{const s=await(await fetch('/api/system')).json();function fmtBytes(b){if(b>=1048576)return(b/1048576).toFixed(1)+' MB';if(b>=1024)return(b/1024).toFixed(1)+' KB';return b+' B'}function fmtUpt(sec){const d=Math.floor(sec/86400),h=Math.floor((sec%86400)/3600),m=Math.floor((sec%3600)/60);let r='';if(d>0)r+=d+'d ';if(h>0||d>0)r+=h+'h ';r+=m+'m';return r}function row(k,v){return '<div style=\"display:flex;justify-content:space-between;font-size:.85rem;padding:5px 0\"><span style=\"color:var(--mut)\">'+k+'</span><span style=\"font-weight:500\">'+v+'</span></div>'}var ramVal=fmtBytes(s.heap_total-s.heap_free)+' / '+fmtBytes(s.heap_total)+' ('+s.heap_used_pct+'%)';let h='';h+=row('Uptime',fmtUpt(s.uptime_s));h+=row('RSSI',(s.wifi_rssi||'--')+' dBm');h+=row('IP',s.ip||'--');h+=row('RAM (heap)',ramVal);h+=row('Liczniki',s.meter_count!=null?s.meter_count:'--');el.innerHTML=h}catch(e){el.innerHTML='<div class=\"empty\">Błąd ładowania danych systemowych</div>'}}\n"
"async function fetchLogs(){try{let t=await(await fetch('/api/logs')).text();t=stripAnsi(t);const el=document.getElementById('log-output');if(!el)return;const b=el.scrollHeight-el.scrollTop-el.clientHeight<40;el.textContent=t||'(brak logow)';if(b)el.scrollTop=el.scrollHeight}catch(e){}}\n"
"async function clearLogs(){try{await fetch('/api/logs/clear',{method:'POST'});document.getElementById('log-output').textContent='(wyczyszczono)'}catch(e){}}\n"
"async function loadLed(){try{const d=await(await fetch('/api/led')).json();var en=document.getElementById('led-en');var br=document.getElementById('led-br');var bv=document.getElementById('led-bv');if(en)en.checked=d.enabled;if(br)br.value=d.brightness;if(bv)bv.textContent=d.brightness+'%'}catch(e){}}\n"
"async function loadLedStatus(){try{const d=await(await fetch('/api/led-status')).json();var en=document.getElementById('leds-en');var br=document.getElementById('leds-br');var bv=document.getElementById('leds-bv');if(en)en.checked=d.enabled;if(br)br.value=d.brightness;if(bv)bv.textContent=d.brightness+'%'}catch(e){}}\n"
"async function saveLed(){var en=document.getElementById('led-en');var br=document.getElementById('led-br');var msg=document.getElementById('led-msg');try{await fetch('/api/led',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:en.checked,brightness:parseInt(br.value)})});if(msg){msg.textContent='Zapisano';setTimeout(function(){msg.textContent=''},2000)}}catch(e){if(msg)msg.textContent='Błąd zapisu'}}\n"
"async function saveLedStatus(){var en=document.getElementById('leds-en');var br=document.getElementById('leds-br');var msg=document.getElementById('leds-msg');try{await fetch('/api/led-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:en.checked,brightness:parseInt(br.value)})});if(msg){msg.textContent='Zapisano';setTimeout(function(){msg.textContent=''},2000)}}catch(e){if(msg)msg.textContent='Błąd zapisu'}}\n"
"async function saveWifi(){const s=document.getElementById('ssid').value.trim(),p=document.getElementById('pass').value,msg=document.getElementById('wifi-msg');if(!s){msg.className='msg err';msg.textContent='Podaj nazwę sieci!';return}msg.className='msg ok';msg.textContent='Zapisywanie...';try{await fetch('/api/config/wifi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:s,password:p})})}catch(e){}msg.textContent='Zapisano - moduł restartuje się i łączy z '+s}\n"
"async function otaGithub(channel){const msg=document.getElementById('ota-msg'),pb=document.getElementById('ota-pbar');var nazwa=channel==='beta'?'beta':'oficjalnej';if(!confirm('Pobrać i wgrać najnowszy firmware ('+nazwa+')?'))return;msg.className='msg ok';msg.textContent='Moduł łączy się z GitHub ('+nazwa+')...';pb.style.display='block';try{await fetch('/api/ota/github?channel='+(channel==='beta'?'beta':'stable'),{method:'POST'});if(otaPoller)clearInterval(otaPoller);otaPoller=setInterval(pollOta,1500)}catch(e){msg.className='msg err';msg.textContent='Blad: '+e}}\n"
"async function pollOta(){try{const d=await(await fetch('/api/ota/status')).json();document.getElementById('ota-bar').style.width=d.progress+'%';const L={idle:'',downloading:'Pobieranie...',writing:'Zapisywanie '+d.progress+'%',success:'OK - restart...',failed:'Blad: '+d.error,uptodate:d.error||'Zainstalowana wersja jest aktualna'};const msg=document.getElementById('ota-msg');if(d.state!=='idle')msg.textContent=L[d.state]||d.state;msg.className=d.state==='failed'?'msg err':(d.state==='uptodate'?'msg ok':'msg ok');if(d.state==='uptodate'){document.getElementById('ota-pbar').style.display='none'}if(d.state==='success'||d.state==='failed'||d.state==='uptodate'){clearInterval(otaPoller);otaPoller=null}}catch(e){}}\n"
"async function checkAvailableVersions(){var es=document.getElementById('ver-stable'),eb=document.getElementById('ver-beta');try{var rels=await(await fetch('https://api.github.com/repos/smartinhome/SIHOS17/releases')).json();if(!Array.isArray(rels)){if(es)es.textContent='';if(eb)eb.textContent='';return}var stable=null,beta=null;for(var i=0;i<rels.length;i++){var r=rels[i];if(r.draft)continue;var tag=r.tag_name||'';var isBeta=tag.toLowerCase().indexOf('beta')>=0;if(isBeta){if(!beta)beta=tag}else{if(!stable)stable=tag}if(stable&&beta)break}var cur=window._fwVersion||'';function fmt(tag,el){if(!el)return;if(!tag){el.textContent='Brak wydania';return}var same=cur&&(tag===cur||tag==='v'+cur||tag.replace(/^v/,'')===cur.replace(/^v/,''));if(same){el.innerHTML='<span style=\\\"color:var(--ok)\\\">Masz najnowszą ('+tag+')</span>'}else{el.innerHTML='Dostępna: <b style=\\\"color:var(--accent)\\\">'+tag+'</b>'}}fmt(stable,es);fmt(beta,eb)}catch(e){if(es)es.textContent='Nie sprawdzono';if(eb)eb.textContent='Nie sprawdzono'}}\n"
"function doBackup(){var m=document.getElementById('bak-msg');if(m){m.textContent='Tworzenie kopii...';m.style.color='var(--mut)'}var a=document.createElement('a');a.href='/api/backup';a.download='sih-backup.sihbak';document.body.appendChild(a);a.click();document.body.removeChild(a);if(m)setTimeout(function(){m.textContent='Kopia pobrana.';setTimeout(function(){m.textContent=''},3000)},800)}\n"
"async function doRestore(input){var f=input.files&&input.files[0];if(!f)return;if(!confirm('Przywrócenie kopii nadpisze zapisane liczniki i historię (ustawienia WiFi/diod pozostaną), a moduł zostanie zrestartowany. Kontynuować?')){input.value='';return}var m=document.getElementById('bak-msg');if(m){m.textContent='Przywracanie kopii...';m.style.color='var(--warn)'}try{var buf=await f.arrayBuffer();var r=await fetch('/api/backup',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:buf});if(r.ok){if(m)m.textContent='Kopia przywrócona. Moduł restartuje się...';setTimeout(function(){location.reload()},15000)}else{var t=await r.text();if(m){m.textContent='Blad: '+t;m.style.color='var(--err)'}}}catch(e){if(m){m.textContent='Błąd odczytu pliku';m.style.color='var(--err)'}}input.value=''}\n"
"async function doRestart(){if(!confirm('Uruchomić ponownie moduł? Potrwa to około 10-15 sekund.'))return;var m=document.getElementById('sys-msg');if(m){m.textContent='Restartowanie...';m.style.color='var(--warn)'}try{await fetch('/api/restart',{method:'POST'})}catch(e){}if(m)m.textContent='Moduł się restartuje. Strona przeładuje się za chwilę.';setTimeout(function(){location.reload()},15000)}\n"
"async function doFactoryReset(){if(!confirm('UWAGA! Przywrócenie ustawień fabrycznych usunie WSZYSTKIE liczniki, klucze AES, ustawienia WiFi i historię. Tej operacji nie da się cofnąć. Kontynuować?'))return;if(!confirm('Na pewno? To ostatnie ostrzeżenie - cała konfiguracja zostanie skasowana.'))return;var m=document.getElementById('sys-msg');if(m){m.textContent='Przywracanie ustawień fabrycznych...';m.style.color='var(--err)'}try{await fetch('/api/factory-reset',{method:'POST'})}catch(e){}if(m)m.textContent='Ustawienia skasowane. Moduł restartuje się w trybie AP (SIH-wMbus).';setTimeout(function(){location.reload()},15000)}\n"
"async function toggleTrack(key,btn){if(!window.TRACKED)window.TRACKED={};var on=!window.TRACKED[key];window.TRACKED[key]=on;if(btn){btn.textContent=on?'\\u2713':'+';if(on){btn.classList.add('on')}else{btn.classList.remove('on')}btn.title=on?'Śledzone w historii':'Dodaj do historii'}try{await fetch('/api/history/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:key,tracked:on})})}catch(e){}}\n"
"async function exportHistCsv(){var list=(window._histList2||window._histList||[]).filter(function(m){return m.tracked!==false});if(!list.length){alert('Brak danych do eksportu');return}var btn=document.getElementById('hist-csv');var old=btn?btn.textContent:'';if(btn){btn.textContent='Pobieranie...';btn.disabled=true}try{var res=histState.res;var cols=[];var rowsMap={};for(var i=0;i<list.length;i++){var id=list[i].id;var url;if(res==='day1'){var a=new Date(histState.anchor*1000);var dv=a.getFullYear()+'-'+String(a.getMonth()+1).padStart(2,'0')+'-'+String(a.getDate()).padStart(2,'0');url='/api/history/day?id='+id+'&date='+dv}else{url='/api/history?id='+id+'&res='+res}var d=JSON.parse(await (await fetch(url)).text());var parts=id.split(':');var dev=parts[0];var nm=(window.NAMES&&window.NAMES[dev.toLowerCase()])||dev;var pole=parts[1]?parts[1].replace(/_/g,' '):'total';var col=nm+' '+pole;cols.push(col);var pts=(d&&d.points)||[];for(var j=0;j<pts.length;j++){var t=pts[j].t;if(!rowsMap[t])rowsMap[t]={};rowsMap[t][col]=pts[j].v}}var times=Object.keys(rowsMap).map(Number).sort(function(x,y){return x-y});var sep=';';var head=['Data','Czas'].concat(cols).join(sep);var lines=[head];for(var k=0;k<times.length;k++){var ts=times[k];var dt=new Date(ts*1000);var dstr=dt.getFullYear()+'-'+String(dt.getMonth()+1).padStart(2,'0')+'-'+String(dt.getDate()).padStart(2,'0');var tstr=String(dt.getHours()).padStart(2,'0')+':'+String(dt.getMinutes()).padStart(2,'0');var row=[dstr,tstr];for(var c=0;c<cols.length;c++){var v=rowsMap[ts][cols[c]];row.push(v!=null?String(v).replace('.',','):'')}lines.push(row.join(sep))}var csv='\\ufeff'+lines.join('\\r\\\n"
"');var blob=new Blob([csv],{type:'text/csv;charset=utf-8'});var a2=document.createElement('a');a2.href=URL.createObjectURL(blob);var now=new Date();a2.download='historia_'+res+'_'+now.getFullYear()+String(now.getMonth()+1).padStart(2,'0')+String(now.getDate()).padStart(2,'0')+'.csv';document.body.appendChild(a2);a2.click();document.body.removeChild(a2);URL.revokeObjectURL(a2.href)}catch(e){alert('Blad eksportu: '+(e&&e.message?e.message:e))}finally{if(btn){btn.textContent=old;btn.disabled=false}}}\n"
"async function loadHistory(silent){if(!histState.id)return;const el=document.getElementById('hist-chart');if(!silent)el.innerHTML='<div class=\"empty\">Ladowanie...</div>';try{var url;if(histState.res==='day1'){var a=new Date(histState.anchor*1000);var dv=a.getFullYear()+'-'+String(a.getMonth()+1).padStart(2,'0')+'-'+String(a.getDate()).padStart(2,'0');url='/api/history/day?id='+histState.id+'&date='+dv}else{url='/api/history?id='+histState.id+'&res='+histState.res}const txt=await(await fetch(url)).text();if(txt===window._histLast&&silent)return;window._histLast=txt;const d=JSON.parse(txt);renderChart(d)}catch(e){if(!silent)el.innerHTML='<div class=\"empty\">Błąd ładowania</div>'}}\n"
"function shiftPeriod(delta){var a=histState.anchor?new Date(histState.anchor*1000):new Date();var r=histState.res;if(r==='hour'||r==='day1')a.setDate(a.getDate()+delta);else if(r==='day')a.setDate(a.getDate()+delta*7);else if(r==='month')a.setMonth(a.getMonth()+delta);else if(r==='year')a.setFullYear(a.getFullYear()+delta);else return;var now=new Date();if(a>now)return;histState.anchor=Math.floor(a.getTime()/1000);window._histLast=null;updatePeriodLabel();loadHistory()}\n"
"async function togglePin(id,btn){if(!window.PINNED)window.PINNED={};id=(id||'').toLowerCase();var on=!window.PINNED[id];window.PINNED[id]=on;if(btn){btn.textContent=on?'\\u2713':'+';if(on){btn.classList.add('on')}else{btn.classList.remove('on')}btn.title=on?'Na dashboard':'Dodaj do dashboard'}try{await fetch('/api/dashboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id,pinned:on})})}catch(e){}var dm=document.getElementById('dash-meters');if(dm)fetchMeters()}// Globalne zmienne stanu przeniesione z oryginalnego UI (OTA, logi, historia)\n"
"let otaPoller=null,logTimer=null,logAuto=true;\n"
"let histState={id:null,res:'hour',anchor:null};\n"
"\n"
"function startLogs(){fetchLogs();if(logTimer)clearInterval(logTimer);if(logAuto)logTimer=setInterval(fetchLogs,2000)}\n"
"\n"
"\n"
"// ===== STAN NOWEGO UI =====\n"
"var UI={view:'meter',focusMeter:null,range:'week',subField:null,lang:'pl',\n"
"  calOpen:false,calView:'days',calY:2026,calM:5,selDay:15,selM:5,selY:2026};\n"
"var _METERS=[];        // wykryte+zapisane liczniki z /api/frames + /api/history/list\n"
"var _FRAMES={};        // ostatnie ramki per id\n"
"var _HISTDAY=null;     // dane wykresu\n"
"\n"
"// medium -> kolor (z zatwierdzonego wygladu)\n"
"function mediaOf(kind){\n"
"  return ({2:{a:'#E0A100',t:'#FBF1D6',n:'Energia'},\n"
"           1:{a:'#2F7FE0',t:'#E2ECFB',n:'Woda'},\n"
"           3:{a:'#E2662E',t:'#FBE7DC',n:'Gaz'},\n"
"           4:{a:'#D6413F',t:'#FBE2E1',n:'Ciepło'}})[kind]||{a:'#6B7280',t:'#EEF0F3',n:'Licznik'};\n"
"}\n"
"\n"
"// ===== ŁADOWANIE DANYCH - uzywa sprawdzonego fetchFrames ze starego UI =====\n"
"async function loadMeters(){\n"
"  try{\n"
"    // fetchFrames: dekoduje /api/frames (hex), scala pola, zwraca liste licznikow\n"
"    var list=await fetchFrames();\n"
"    if(!Array.isArray(list)){return;}\n"
"    // pobierz nazwy uzytkownika i tracked (jak stary fetchMeters)\n"
"    try{const nm=await(await fetch('/api/meter/names')).json();window.NAMES={};for(const k in nm)window.NAMES[k.toLowerCase()]=nm[k];}catch(e){}\n"
"    try{const tr=await(await fetch('/api/history/tracked')).json();window.TRACKED={};tr.forEach(function(k){window.TRACKED[k]=true;});}catch(e){}\n"
"    _METERS=list.map(function(o){return {\n"
"      id:o.id,kind:kindOf(o),name:nameOf(o),mfct:o.manufacturer,\n"
"      fields:o.fields||[],keyError:o._keyError,rssi:o.rssi,ts:o._tsUnix||o._ts||o.ts\n"
"    };});\n"
"    if(!UI.focusMeter&&_METERS.length)UI.focusMeter=_METERS[0].id;\n"
"  }catch(e){console.warn('loadMeters',e);}\n"
"}\n"
"// typ medium z wyniku dekodera\n"
"function kindOf(o){\n"
"  if(o.type==='amiplus')return 2;\n"
"  if(o.type==='sontex')return 4;\n"
"  if(o.type==='gas'||o.type==='unismart')return 3;\n"
"  return 1; // izar, apator, op041a, woda\n"
"}\n"
"function nameOf(o){\n"
"  const names={amiplus:'Amiplus',izar:'Diehl IZAR',unismart:'Unismart',sontex:'Sontex microclima',op041a:'Apator op041a',apator:'Apator',apator162:'Apator 162',gas:'Gaz',unknown:'Licznik'};\n"
"  if(window.NAMES&&window.NAMES[(o.id||'').toLowerCase()])return window.NAMES[(o.id||'').toLowerCase()];\n"
"  return names[o.type]||'Licznik';\n"
"}\n"
"\n"
"// ===== RENDER: lewa szyna z realnymi licznikami =====\n"
"function renderRail(){\n"
"  var meters=_METERS.map(function(m){\n"
"    var a=UI.view==='meter'&&UI.focusMeter===m.id;var md=mediaOf(m.kind);\n"
"    var mf=mainField(m);\n"
"    var big=mf?fmtFieldVal(mf):(m.keyError?'🔑':'—');\n"
"    var unit=mf?(mf.unit||''):'';\n"
"    return '<div data-nav=\"meter\" data-id=\"'+m.id+'\" style=\"display:flex;align-items:center;gap:12px;padding:13px 14px;cursor:pointer;border-radius:13px;background:'+(a?'#fff':'transparent')+';border:1px solid '+(a?'#EAECEF':'transparent')+';border-left:3px solid '+(a?md.a:'transparent')+';box-shadow:'+(a?'0 2px 8px rgba(16,24,40,.07)':'none')+';\">'+\n"
"      '<span style=\"width:9px;height:9px;border-radius:50%;flex:none;background:'+md.a+';\"></span>'+\n"
"      '<div style=\"flex:1;min-width:0;\"><div style=\"font:600 14px Manrope,sans-serif;color:#2C323B;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;\">'+esc(m.name)+'</div><div style=\"font:500 10.5px Manrope,sans-serif;color:#AEB3BB;\">'+esc(m.id)+' · '+esc(m.mfct||'')+'</div></div>'+\n"
"      '<div style=\"text-align:right;flex:none;\"><span style=\"font:700 14px \\'Space Grotesk\\',sans-serif;color:#16181D;\">'+big+'</span> <span style=\"font:600 10px Manrope,sans-serif;color:#9AA0AA;\">'+esc(unit)+'</span></div>'+\n"
"    '</div>';\n"
"  }).join('')||'<div style=\"font:500 13px Manrope,sans-serif;color:#AEB3BB;padding:10px 4px;\">Brak wykrytych liczników</div>';\n"
"  var sysDefs=[['add','Dodaj licznik','M12 5v14M5 12h14'],['led','Dioda LED','M9 18h6M10 21h4M8.6 15A6 6 0 1 1 12 3a6 6 0 0 1 3.4 12z'],['wifi','Wi-Fi','M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0M12 19.5h.01'],['info','Informacje','M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20zM12 11v5M12 8h.01'],['update','Aktualizacja','M20 12a8 8 0 1 1-2.3-5.7M20 4v4.5h-4.5'],['logs','Logi','M4 6h16M4 12h16M4 18h10']];\n"
"  var sysItems=sysDefs.map(function(d){var a=UI.view===d[0];\n"
"    return '<div data-nav=\"'+d[0]+'\" style=\"display:flex;align-items:center;gap:12px;padding:11px 14px;cursor:pointer;border-radius:13px;background:'+(a?'#fff':'transparent')+';border:1px solid '+(a?'#EAECEF':'transparent')+';border-left:3px solid '+(a?'#16181D':'transparent')+';box-shadow:'+(a?'0 2px 8px rgba(16,24,40,.07)':'none')+';\">'+\n"
"      '<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"'+(a?'#16181D':'#8A909A')+'\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"'+d[2]+'\"/></svg>'+\n"
"      '<div style=\"flex:1;font:600 14px Manrope,sans-serif;color:#2C323B;\">'+d[1]+'</div></div>';\n"
"  }).join('');\n"
"  return '<div style=\"width:326px;flex:none;box-sizing:border-box;background:#F7F8FA;border-right:1px solid #EAECEF;padding:24px 22px;display:flex;flex-direction:column;\">'+\n"
"    '<div style=\"display:flex;align-items:center;justify-content:space-between;\"><span style=\"font:700 14px \\'Space Grotesk\\',sans-serif;letter-spacing:.13em;color:#16181D;\">SIHOS17</span></div>'+\n"
"    '<div style=\"font:700 11px Manrope,sans-serif;color:#AEB3BB;text-transform:uppercase;letter-spacing:.08em;margin:20px 0 10px;\">Liczniki</div>'+\n"
"    '<div style=\"display:flex;flex-direction:column;gap:6px;\">'+meters+'</div>'+\n"
"    '<div style=\"font:700 11px Manrope,sans-serif;color:#AEB3BB;text-transform:uppercase;letter-spacing:.08em;margin:20px 0 10px;\">System</div>'+\n"
"    '<div style=\"display:flex;flex-direction:column;gap:5px;\">'+sysItems+'</div>'+\n"
"  '</div>';\n"
"}\n"
"// Wybor glownej wartosci: pierwsze pole kumulacyjne (kWh/m3/GJ), inaczej pierwsze liczbowe\n"
"function mainField(m){\n"
"  if(!m.fields||!m.fields.length)return null;\n"
"  var cum=m.fields.find(function(x){return x.unit==='kWh'||x.unit==='m3'||x.unit==='GJ';});\n"
"  if(cum)return cum;\n"
"  var num=m.fields.find(function(x){return typeof x.value==='number'&&isFinite(x.value);});\n"
"  return num||m.fields[0];\n"
"}\n"
"function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}\n"
"// Formatowanie wartosci - DOKLADNIE jak stary UI (fieldGroup)\n"
"function fmtFieldVal(f){\n"
"  var x=f;\n"
"  if(typeof x.value==='number'&&isFinite(x.value)){\n"
"    if(x.unit==='V'||x.unit==='s'||x.unit==='W')return Math.round(x.value).toString();\n"
"    if(x.unit==='lat')return x.value.toFixed(1);\n"
"    if(x.unit==='m3'||x.unit==='kWh'||x.unit==='kW')return x.value.toFixed(3);\n"
"    return x.value.toFixed(2);\n"
"  }\n"
"  return esc(x.value);\n"
"}\n"
"\n"
"// ===== RENDER: detal licznika (realne pola + sledzenie + na zywo + wykres) =====\n"
"function fieldLabel(f){\n"
"  // etykieta jak stary UI: podkreslenia na spacje, z opcjonalna ladna nazwa\n"
"  var map={energia_kwh:'Energia łącznie',energia_t1_kwh:'Energia T1',energia_t2_kwh:'Energia T2',energia_t3_kwh:'Energia T3',produkcja_kwh:'Produkcja',moc_kw:'Moc',moc_produkcji_kw:'Moc produkcji',napiecie_l1_v:'Napięcie L1',napiecie_l2_v:'Napięcie L2',napiecie_l3_v:'Napięcie L3',total_m3:'Objętość',poprzedni_miesiac_m3:'Poprzedni miesiąc',data_odczytu:'Data odczytu',bateria_lata:'Bateria',okres_nadawania_s:'Okres nadawania',alarm:'Alarm'};\n"
"  return map[f.field]||(f.field?f.field.replace(/_/g,' '):'');\n"
"}\n"
"function isTrackable(f){return typeof f.value==='number'&&['energia_kwh','energia_t1_kwh','energia_t2_kwh','energia_t3_kwh','produkcja_kwh','total_m3','moc_kw','napiecie_l1_v','napiecie_l2_v','napiecie_l3_v'].indexOf(f.field)>=0;}\n"
"\n"
"function renderMeterDetail(){\n"
"  var m=_METERS.find(function(x){return x.id===UI.focusMeter;});\n"
"  if(!m)return '<div style=\"font:500 14px Manrope,sans-serif;color:#AEB3BB;\">Wybierz licznik z listy</div>';\n"
"  var md=mediaOf(m.kind);\n"
"  var mf=mainField(m);\n"
"  var big=mf?fmtFieldVal(mf):'—';\n"
"  var unit=mf?(mf.unit||''):'';\n"
"  // pasek na zywo\n"
"  var live='<div style=\"display:flex;align-items:center;gap:14px;margin-top:20px;padding:12px 16px;background:#F0FAF4;border:1px solid #CDE6D6;border-radius:13px;\">'+\n"
"    '<span style=\"width:8px;height:8px;border-radius:50%;background:#2FA36B;flex:none;\"></span>'+\n"
"    '<span style=\"font:700 12px Manrope,sans-serif;color:#2FA36B;text-transform:uppercase;letter-spacing:.05em;\">Odczyt na żywo</span>'+\n"
"    '<span style=\"font:600 12.5px Manrope,sans-serif;color:#5A616C;\">ostatnia ramka: '+(m.ts?timeOnly(m.ts):'—')+'</span>'+\n"
"    '<span style=\"margin-left:auto;font:600 12.5px Manrope,sans-serif;color:#5A616C;\">RSSI: <b style=\"color:#2C323B;\">'+(m.rssi||'—')+' dBm</b></span>'+\n"
"  '</div>';\n"
"  // kafelki pol z przyciskiem sledzenia\n"
"  var tiles;\n"
"  if(!m.fields||!m.fields.length){\n"
"    if(m.keyError==='nokey')tiles='<div style=\"color:#e0a800;font:600 13px Manrope,sans-serif;padding:8px 0;\">Brak klucza AES — dodaj klucz dla tego licznika w zakładce Dodaj licznik.</div>';\n"
"    else if(m.keyError==='badkey')tiles='<div style=\"color:#e5484d;font:600 13px Manrope,sans-serif;padding:8px 0;\">Klucz niepoprawny — sprawdź klucz AES dla tego licznika.</div>';\n"
"    else tiles='<div style=\"color:#9AA0AA;font:500 13px Manrope,sans-serif;padding:8px 0;\">Brak pól w tej ramce.</div>';\n"
"  }else tiles=m.fields.map(function(f){\n"
"    var active=UI.subField===f.field;var trk=isTrackable(f);\n"
"    var tkey=m.id+':'+f.field;var isTr=window.TRACKED&&window.TRACKED[tkey];\n"
"    var st='flex:1 1 165px;border-radius:14px;padding:14px 16px;transition:.15s;'+(trk?'cursor:pointer;background:'+(active?md.t:'#F6F7F9')+';border:1px solid '+(active?md.a:'#EEF0F3')+';':'background:#F6F7F9;border:1px solid #EEF0F3;');\n"
"    var lc=active?md.a:'#9AA0AA';\n"
"    var trackBtn=trk?'<span data-track=\"'+tkey+'\" title=\"Śledź w historii\" style=\"display:inline-flex;align-items:center;justify-content:center;width:22px;height:22px;border-radius:7px;cursor:pointer;flex:none;background:'+(isTr?'#2FA36B':'#EDEEF1')+';color:'+(isTr?'#fff':'#9AA0AA')+';font:700 14px Manrope,sans-serif;\">'+(isTr?'✓':'+')+'</span>':'';\n"
"    return '<div data-field=\"'+(trk?f.field:'')+'\" style=\"'+st+'\">'+\n"
"      '<div style=\"display:flex;align-items:center;justify-content:space-between;gap:6px;\"><div style=\"font:600 11px Manrope,sans-serif;color:'+lc+';text-transform:uppercase;letter-spacing:.04em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;\">'+esc(fieldLabel(f))+'</div>'+trackBtn+'</div>'+\n"
"      '<div style=\"font:700 22px \\'Space Grotesk\\',sans-serif;color:#2C323B;margin-top:7px;white-space:nowrap;\">'+fmtFieldVal(f)+' <span style=\"font:600 12px Manrope,sans-serif;color:#9AA0AA;\">'+esc(f.unit||'')+'</span></div>'+\n"
"    '</div>';\n"
"  }).join('');\n"
"  // wykres (dane z _HISTDAY jesli sa, inaczej placeholder)\n"
"  var chart=renderHistChart(md.a);\n"
"  var rangeBtns=[['day','Dzień'],['week','Tydzień'],['month','Miesiąc'],['year','Rok']].map(function(d){var a=UI.range===d[0];return '<button data-range=\"'+d[0]+'\" style=\"padding:8px 14px;border:none;cursor:pointer;border-radius:999px;font:600 12.5px Manrope,sans-serif;'+(a?'background:#16181D;color:#fff;':'background:transparent;color:#6B7280;')+'\">'+d[1]+'</button>';}).join('');\n"
"  return '<div style=\"display:flex;align-items:center;gap:16px;\">'+\n"
"    '<div style=\"width:56px;height:56px;border-radius:16px;display:flex;align-items:center;justify-content:center;background:'+md.t+';\"><div style=\"width:22px;height:22px;border-radius:8px;background:'+md.a+';\"></div></div>'+\n"
"    '<div><div style=\"font:600 12.5px Manrope,sans-serif;color:#9AA0AA;\">Szczegóły licznika</div><div style=\"font:700 24px \\'Space Grotesk\\',sans-serif;color:#16181D;margin-top:2px;\">'+esc(m.name)+' <span style=\"font:500 13px Manrope,sans-serif;color:#AEB3BB;\">'+esc(m.id)+'</span></div></div>'+\n"
"    '<div style=\"margin-left:auto;text-align:right;\"><span style=\"font:700 44px \\'Space Grotesk\\',sans-serif;color:#16181D;\">'+big+'</span> <span style=\"font:600 18px Manrope,sans-serif;color:#9AA0AA;\">'+esc(unit)+'</span></div>'+\n"
"  '</div>'+live+\n"
"  '<div style=\"display:flex;flex-wrap:wrap;gap:12px;margin-top:16px;\">'+tiles+'</div>'+\n"
"  '<div style=\"margin-top:26px;\"><div style=\"display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap;\">'+\n"
"    '<span style=\"font:600 17px \\'Space Grotesk\\',sans-serif;color:#16181D;\">Historia zużycia</span>'+\n"
"    '<div style=\"display:flex;gap:2px;background:#F0F1F4;border-radius:999px;padding:3px;\">'+rangeBtns+'</div>'+\n"
"  '</div>'+chart+'</div>';\n"
"}\n"
"function renderHistChart(color){\n"
"  // Jesli sa realne dane z /api/history/day - pokaz, inaczej pusto\n"
"  if(!_HISTDAY||!_HISTDAY.length)return '<div style=\"display:flex;align-items:center;justify-content:center;height:190px;margin-top:22px;color:#C3C7CE;font:500 13px Manrope,sans-serif;\">Brak danych historii dla tego okresu</div>';\n"
"  var mx=Math.max.apply(null,_HISTDAY.map(function(p){return p.v;}))||1;\n"
"  var bars=_HISTDAY.map(function(p){var h=Math.round(p.v/mx*100);\n"
"    return '<div style=\"flex:1;min-width:0;height:100%;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:8px;\"><div style=\"width:100%;height:'+h+'%;min-height:4px;background:'+color+';border-radius:5px 5px 3px 3px;\"></div></div>';\n"
"  }).join('');\n"
"  return '<div style=\"display:flex;align-items:flex-end;gap:5px;height:190px;margin-top:22px;\">'+bars+'</div>';\n"
"}\n"
"\n"
"// ===== PANELE SYSTEM (podpiete pod realne API-glue) =====\n"
"function sysHead(t){return '<div style=\"font:600 12.5px Manrope,sans-serif;color:#9AA0AA;\">System</div><div style=\"font:700 24px \\'Space Grotesk\\',sans-serif;color:#16181D;margin-top:2px;margin-bottom:22px;\">'+t+'</div>';}\n"
"\n"
"function renderAdd(){\n"
"  return sysHead('Dodaj licznik')+\n"
"    '<div style=\"background:#F6F7F9;border:1px solid #EEF0F3;border-radius:16px;padding:20px 22px;margin-bottom:14px;\">'+\n"
"      '<div style=\"font:600 11px Manrope,sans-serif;color:#9AA0AA;text-transform:uppercase;letter-spacing:.05em;margin-bottom:12px;\">Klucz AES (liczniki szyfrowane)</div>'+\n"
"      '<div style=\"display:flex;gap:10px;flex-wrap:wrap;\"><input id=\"keyid\" type=\"text\" placeholder=\"ID np. 56989134\" style=\"flex:1;min-width:150px;\"><input id=\"keyval\" type=\"text\" placeholder=\"klucz AES 32 hex\" style=\"flex:2;min-width:220px;\"><button data-do=\"saveKey\" style=\"padding:11px 22px;border:none;border-radius:11px;background:#16181D;color:#fff;font:700 13.5px Manrope,sans-serif;cursor:pointer;\">Zapisz</button></div>'+\n"
"      '<div id=\"keymsg\" style=\"font:600 12px Manrope,sans-serif;margin-top:8px;\"></div>'+\n"
"    '</div>'+\n"
"    '<div style=\"background:#F6F7F9;border:1px solid #EEF0F3;border-radius:16px;padding:20px 22px;margin-bottom:14px;\"><div style=\"font:600 11px Manrope,sans-serif;color:#9AA0AA;text-transform:uppercase;letter-spacing:.05em;margin-bottom:12px;\">Zapisane liczniki z kluczem</div><div id=\"saved-list\" style=\"display:flex;flex-direction:column;gap:8px;\"><div style=\"font:500 13px Manrope,sans-serif;color:#AEB3BB;\">Ładuję...</div></div></div>'+\n"
"    '<div style=\"background:#F6F7F9;border:1px solid #EEF0F3;border-radius:16px;padding:20px 22px;\"><div style=\"font:600 11px Manrope,sans-serif;color:#9AA0AA;text-transform:uppercase;letter-spacing:.05em;margin-bottom:12px;\">Wykryte liczniki</div><div id=\"detected-list\" style=\"display:flex;flex-direction:column;gap:8px;\"></div></div>';\n"
"}\n"
"function renderLogs(){\n"
"  return sysHead('Logi')+\n"
"    '<div style=\"display:flex;justify-content:flex-end;margin-bottom:12px;\"><button data-do=\"clearLogs\" style=\"padding:10px 18px;border:1px solid #E7E9ED;border-radius:11px;background:#fff;font:600 13px Manrope,sans-serif;color:#3A414B;cursor:pointer;\">Wyczyść</button></div>'+\n"
"    '<div id=\"log-output\" style=\"background:#F6F7F9;border:1px solid #EEF0F3;border-radius:14px;padding:16px 18px;min-height:200px;max-height:440px;overflow:auto;font:500 12px monospace;color:#5A616C;white-space:pre-wrap;\">Ładowanie...</div>';\n"
"}\n"
"\n"
"// ===== GŁÓWNY RENDER =====\n"
"function renderUI(){\n"
"  var detail='';\n"
"  if(UI.view==='meter')detail=renderMeterDetail();\n"
"  else if(UI.view==='add')detail=renderAdd();\n"
"  else if(UI.view==='logs')detail=renderLogs();\n"
"  else if(UI.view==='led')detail=sysHead('Dioda LED')+renderLedPanel();\n"
"  else if(UI.view==='wifi')detail=sysHead('Wi-Fi')+renderWifiPanel();\n"
"  else if(UI.view==='info')detail=sysHead('Informacje')+'<div id=\"sysinfo\">Ładowanie...</div>';\n"
"  else if(UI.view==='update')detail=sysHead('Aktualizacja')+renderUpdatePanel();\n"
"  var app=document.getElementById('app');\n"
"  if(app)app.innerHTML='<div style=\"width:1220px;max-width:100%;box-sizing:border-box;background:#fff;border-radius:24px;border:1px solid #E3E5E9;overflow:hidden;display:flex;font-family:Manrope,sans-serif;box-shadow:0 2px 6px rgba(16,24,40,.05);\">'+renderRail()+'<div style=\"flex:1;min-width:0;padding:30px 34px;\">'+detail+'</div></div>';\n"
"  // po renderze - dociagnij dane zalezne od widoku\n"
"  if(UI.view==='add'){if(typeof loadSavedMeters==='function')loadSavedMeters();renderDetected();}\n"
"  else if(UI.view==='info'&&typeof fetchSystem==='function')fetchSystem();\n"
"  else if(UI.view==='logs'){if(typeof startLogs==='function')startLogs();else if(typeof fetchLogs==='function')fetchLogs();}\n"
"  else if(UI.view==='led'){if(typeof loadLed==='function')loadLed();if(typeof loadLedStatus==='function')loadLedStatus();}\n"
"  else if(UI.view==='update'&&typeof checkAvailableVersions==='function')checkAvailableVersions();\n"
"}\n"
"function renderDetected(){\n"
"  var box=document.getElementById('detected-list');if(!box)return;\n"
"  var det=_METERS.filter(function(m){return !window.METER_KEYS||!window.METER_KEYS[m.id.toLowerCase()];});\n"
"  box.innerHTML=det.map(function(m){var md=mediaOf(m.kind);\n"
"    return '<div style=\"display:flex;align-items:center;gap:12px;padding:12px 14px;background:#fff;border:1px solid #EEF0F3;border-radius:12px;\"><span style=\"width:8px;height:8px;border-radius:50%;background:'+md.a+';flex:none;\"></span><div style=\"flex:1;\"><div style=\"font:600 14px Manrope,sans-serif;color:#2C323B;\">'+esc(m.name)+'</div><div style=\"font:500 11px Manrope,sans-serif;color:#AEB3BB;\">'+esc(m.id)+' · '+esc(m.mfct||'')+'</div></div><button data-add=\"'+m.id+'\" style=\"padding:8px 15px;border:none;border-radius:10px;background:#16181D;color:#fff;font:600 12.5px Manrope,sans-serif;cursor:pointer;\">Dodaj</button></div>';\n"
"  }).join('')||'<div style=\"font:500 13px Manrope,sans-serif;color:#AEB3BB;\">Brak nowych liczników</div>';\n"
"}\n"
"\n"
"// ===== OBSŁUGA ZDARZEŃ =====\n"
"document.addEventListener('click',function(e){\n"
"  var nav=e.target.closest('[data-nav]');\n"
"  var range=e.target.closest('[data-range]');\n"
"  var field=e.target.closest('[data-field]');\n"
"  var track=e.target.closest('[data-track]');\n"
"  var add=e.target.closest('[data-add]');\n"
"  var doBtn=e.target.closest('[data-do]');\n"
"  if(track){e.stopPropagation();var k=track.getAttribute('data-track');if(!window.TRACKED)window.TRACKED={};window.TRACKED[k]=!window.TRACKED[k];if(typeof toggleTrack==='function'){try{toggleTrack(k)}catch(_){}}renderUI();return;}\n"
"  if(nav){var newView=nav.getAttribute('data-nav');\n"
"    // zatrzymaj auto-odswiezanie logow przy wyjsciu z zakladki Logi\n"
"    if(UI.view==='logs'&&newView!=='logs'&&typeof logTimer!=='undefined'&&logTimer){clearInterval(logTimer);logTimer=null;}\n"
"    UI.view=newView;var id=nav.getAttribute('data-id');if(id)UI.focusMeter=id;UI.subField=null;renderUI();return;}\n"
"  if(range){UI.range=range.getAttribute('data-range');loadHistDay();return;}\n"
"  if(field){var f=field.getAttribute('data-field');if(f)UI.subField=UI.subField===f?null:f;renderUI();return;}\n"
"  if(add){UI.view='meter';UI.focusMeter=add.getAttribute('data-add');renderUI();return;}\n"
"  if(doBtn){var act=doBtn.getAttribute('data-do');\n"
"    if(act==='saveKey'&&typeof saveKey==='function')saveKey();\n"
"    else if(act==='clearLogs'&&typeof clearLogs==='function')clearLogs();\n"
"    else if(act==='saveLedBoth'){if(typeof saveLed==='function')saveLed();if(typeof saveLedStatus==='function')saveLedStatus();}\n"
"    else if(act==='saveWifi'&&typeof saveWifi==='function')saveWifi();\n"
"    else if(act==='otaStable'&&typeof otaGithub==='function')otaGithub('stable');\n"
"    else if(act==='otaBeta'&&typeof otaGithub==='function')otaGithub('beta');\n"
"    else if(act==='backup'&&typeof doBackup==='function')doBackup();\n"
"    else if(act==='restart'&&typeof doRestart==='function')doRestart();\n"
"    else if(act==='factory'&&typeof doFactoryReset==='function')doFactoryReset();\n"
"    return;}\n"
"});\n"
"\n"
"// ===== HISTORIA: pobierz dane wykresu z realnego API =====\n"
"async function loadHistDay(){\n"
"  var m=_METERS.find(function(x){return x.id===UI.focusMeter;});\n"
"  if(!m){renderUI();return;}\n"
"  try{\n"
"    var field=UI.subField||(m.fields[0]&&m.fields[0].field)||'';\n"
"    var url='/api/history/day?id='+encodeURIComponent(m.id)+'&field='+encodeURIComponent(field)+'&range='+UI.range;\n"
"    var r=await(await fetch(url)).json();\n"
"    _HISTDAY=r.points||r.data||[];\n"
"  }catch(e){_HISTDAY=[];}\n"
"  renderUI();\n"
"}\n"
"\n"
"// ===== START =====\n"
"async function startUI(){\n"
"  await loadMeters();\n"
"  renderUI();\n"
"  setInterval(async function(){await loadMeters();if(UI.view==='meter')renderUI();},5000);\n"
"}\n"
"if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startUI);\n"
"else startUI();\n"
"\n"
"// ===== PANELE SYSTEM z ID zgodnymi z API-glue =====\n"
"function ledCardHtml(title,sub,enId,brId,bvId,msgId){\n"
"  return '<div style=\"background:#F6F7F9;border:1px solid #EEF0F3;border-radius:16px;padding:20px 22px;\">'+\n"
"    '<div style=\"display:flex;align-items:center;justify-content:space-between;\"><div><div style=\"font:600 15px Manrope,sans-serif;color:#2C323B;\">'+title+'</div><div style=\"font:500 12px Manrope,sans-serif;color:#9AA0AA;margin-top:3px;\">'+sub+'</div></div><label style=\"cursor:pointer;\"><input type=\"checkbox\" id=\"'+enId+'\" style=\"width:20px;height:20px;cursor:pointer;\"></label></div>'+\n"
"    '<div style=\"margin-top:16px;\"><div style=\"display:flex;align-items:center;justify-content:space-between;margin-bottom:10px;\"><span style=\"font:600 11px Manrope,sans-serif;color:#9AA0AA;text-transform:uppercase;letter-spacing:.05em;\">Jasność</span><span id=\"'+bvId+'\" style=\"font:700 14px \\'Space Grotesk\\',sans-serif;color:#2C323B;\">—</span></div><input type=\"range\" id=\"'+brId+'\" min=\"0\" max=\"100\" style=\"width:100%;height:6px;cursor:pointer;\"></div>'+\n"
"    '<div id=\"'+msgId+'\" style=\"font:600 12px Manrope,sans-serif;margin-top:8px;\"></div>'+\n"
"  '</div>';\n"
"}\n"
"function renderLedPanel(){\n"
"  return '<div style=\"display:grid;grid-template-columns:1fr 1fr;gap:14px;\">'+\n"
"    ledCardHtml('LED RX','Mruga przy odbiorze ramek','led-en','led-br','led-bv','led-msg')+\n"
"    ledCardHtml('Dioda status','RGB — status połączenia WiFi','leds-en','leds-br','leds-bv','leds-msg')+\n"
"  '</div><button data-do=\"saveLedBoth\" style=\"margin-top:20px;padding:13px 24px;border:none;border-radius:12px;background:#16181D;color:#fff;font:700 14px Manrope,sans-serif;cursor:pointer;\">Zapisz</button>';\n"
"}\n"
"function renderWifiPanel(){\n"
"  return '<div style=\"font:600 11px Manrope,sans-serif;color:#9AA0AA;text-transform:uppercase;letter-spacing:.05em;margin-bottom:10px;\">Nazwa sieci</div>'+\n"
"    '<input type=\"text\" id=\"ssid\" placeholder=\"SSID\" style=\"width:100%;margin-bottom:14px;\">'+\n"
"    '<div style=\"font:600 11px Manrope,sans-serif;color:#9AA0AA;text-transform:uppercase;letter-spacing:.05em;margin-bottom:10px;\">Hasło WiFi</div>'+\n"
"    '<input type=\"password\" id=\"pass\" placeholder=\"Hasło\" style=\"width:100%;margin-bottom:20px;\">'+\n"
"    '<button data-do=\"saveWifi\" style=\"padding:13px 24px;border:none;border-radius:12px;background:#16181D;color:#fff;font:700 14px Manrope,sans-serif;cursor:pointer;\">Zapisz</button>'+\n"
"    '<div id=\"wifi-msg\" style=\"font:600 12px Manrope,sans-serif;margin-top:10px;\"></div>';\n"
"}\n"
"function renderUpdatePanel(){\n"
"  return '<div style=\"display:flex;gap:12px;margin-bottom:14px;\">'+\n"
"    '<div style=\"flex:1;background:#F6F7F9;border:1px solid #EEF0F3;border-radius:14px;padding:16px 18px;\"><div style=\"font:600 11px Manrope,sans-serif;color:#9AA0AA;text-transform:uppercase;letter-spacing:.05em;\">Wersja oficjalna</div><button data-do=\"otaStable\" style=\"margin-top:12px;width:100%;padding:11px;border:none;border-radius:11px;background:#16181D;color:#fff;font:700 13px Manrope,sans-serif;cursor:pointer;\">Aktualizuj do oficjalnej</button><div id=\"ver-stable\" style=\"font:600 12px Manrope,sans-serif;color:#9AA0AA;margin-top:8px;text-align:center;\">Sprawdzanie...</div></div>'+\n"
"    '<div style=\"flex:1;background:#F6F7F9;border:1px solid #EEF0F3;border-radius:14px;padding:16px 18px;\"><div style=\"font:600 11px Manrope,sans-serif;color:#9AA0AA;text-transform:uppercase;letter-spacing:.05em;\">Wersja beta</div><button data-do=\"otaBeta\" style=\"margin-top:12px;width:100%;padding:11px;border:none;border-radius:11px;background:#16181D;color:#fff;font:700 13px Manrope,sans-serif;cursor:pointer;\">Aktualizuj do beta</button><div id=\"ver-beta\" style=\"font:600 12px Manrope,sans-serif;color:#9AA0AA;margin-top:8px;text-align:center;\">Sprawdzanie...</div></div>'+\n"
"  '</div>'+\n"
"  '<div id=\"ota-msg\" style=\"font:600 12.5px Manrope,sans-serif;margin-top:6px;\"></div>'+\n"
"  '<div id=\"ota-pbar\" style=\"display:none;height:8px;background:#EAECEF;border-radius:999px;margin-top:12px;overflow:hidden;\"><div id=\"ota-bar\" style=\"height:100%;width:0;background:#2FA36B;border-radius:999px;transition:width .2s;\"></div></div>'+\n"
"  '<div style=\"font:600 11px Manrope,sans-serif;color:#9AA0AA;text-transform:uppercase;letter-spacing:.05em;margin:22px 0 12px;\">Zarządzanie</div>'+\n"
"  '<div style=\"display:flex;gap:10px;flex-wrap:wrap;\">'+\n"
"    '<button data-do=\"backup\" style=\"padding:12px 18px;border:1px solid #E7E9ED;border-radius:11px;background:#fff;font:600 13px Manrope,sans-serif;color:#3A414B;cursor:pointer;\">Eksport kopii</button>'+\n"
"    '<label style=\"padding:12px 18px;border:1px solid #E7E9ED;border-radius:11px;background:#fff;font:600 13px Manrope,sans-serif;color:#3A414B;cursor:pointer;\">Import kopii<input type=\"file\" id=\"restore-file\" style=\"display:none;\" onchange=\"if(typeof doRestore===\\'function\\')doRestore(this)\"></label>'+\n"
"    '<button data-do=\"restart\" style=\"padding:12px 18px;border:1px solid #E7E9ED;border-radius:11px;background:#fff;font:600 13px Manrope,sans-serif;color:#3A414B;cursor:pointer;\">Restart</button>'+\n"
"    '<button data-do=\"factory\" style=\"padding:12px 18px;border:1px solid #F0D4D4;border-radius:11px;background:#fff;font:600 13px Manrope,sans-serif;color:#D6413F;cursor:pointer;\">Reset fabryczny</button>'+\n"
"  '</div><div id=\"bak-msg\" style=\"font:600 12px Manrope,sans-serif;margin-top:10px;\"></div>';\n"
"}\n"
"</script></body></html>\n"
"\n";

static esp_err_t root_handler(httpd_req_t *req) {
    httpd_resp_set_type(req, "text/html; charset=utf-8");
    httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
    // Strona jest duza (~70 KB) — wysylamy w kawalkach, by uniknac
    // bledu wysylki (EAGAIN/error 11) przy ograniczonym buforze TCP.
    const char *p = ROOT_HTML;
    size_t remaining = strlen(ROOT_HTML);
    const size_t CHUNK = 2048;
    while (remaining > 0) {
        size_t n = remaining > CHUNK ? CHUNK : remaining;
        esp_err_t err = httpd_resp_send_chunk(req, p, n);
        if (err != ESP_OK) {
            ESP_LOGW(TAG, "root_handler: wysylka przerwana (%s)", esp_err_to_name(err));
            return err;
        }
        p += n;
        remaining -= n;
    }
    httpd_resp_send_chunk(req, NULL, 0);   // koniec
    return ESP_OK;
}

static esp_err_t favicon_handler(httpd_req_t *req) {
    httpd_resp_set_status(req, "204 No Content");
    httpd_resp_send(req, NULL, 0);
    return ESP_OK;
}

void webserver_init(void) {
    httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
    cfg.max_uri_handlers = 32;   // 27 endpointow (api_handlers 25 + / + favicon) z zapasem
    cfg.stack_size       = 8192;
    cfg.lru_purge_enable = true;
    cfg.max_open_sockets = 7;   // limit gniazd httpd; reszta z puli LWIP wolna dla OTA
    ESP_ERROR_CHECK(httpd_start(&s_server, &cfg));
    httpd_uri_t root = {
        .uri          = "/",
        .method       = HTTP_GET,
        .handler      = root_handler,
        .user_ctx     = NULL,
        .is_websocket = false,
    };
    httpd_register_uri_handler(s_server, &root);
    httpd_uri_t favicon = {
        .uri = "/favicon.ico", .method = HTTP_GET,
        .handler = favicon_handler, .user_ctx = NULL, .is_websocket = false,
    };
    httpd_register_uri_handler(s_server, &favicon);
    api_register_handlers(s_server);
    ESP_LOGI(TAG, "Serwer HTTP uruchomiony na porcie 80");
}

void webserver_stop(void) {
    if (s_server) httpd_stop(s_server);
    s_server = NULL;
}
